//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetterAmazer.Business.Services.Data
{
    using System;
    
    public partial class AddressInfo
    {
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string AttPerson { get; set; }
        public string City { get; set; }
        public string CompanyName { get; set; }
        public string Country { get; set; }
        public string CountryCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Postal { get; set; }
        public string VatNr { get; set; }
    }
}
