//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetterAmazer.Business.Services.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Letters = new HashSet<Letter>();
            this.Orders = new HashSet<Order>();
            this.CustomerInfo = new AddressInfo();
        }
    
        public int Id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Username { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public Nullable<decimal> Credits { get; set; }
    
        public AddressInfo CustomerInfo { get; set; }
    
        public virtual ICollection<Letter> Letters { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
