//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetterAmazer.Business.Services.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FulfillmentPartner
    {
        public FulfillmentPartner()
        {
            this.Offices = new HashSet<Office>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int ShopId { get; set; }
    
        public virtual Shop Shop { get; set; }
        public virtual ICollection<Office> Offices { get; set; }
    }
}
