//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetterAmazer.Business.Services.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LetterAmazerContext : DbContext
    {
        public LetterAmazerContext()
            : base("name=LetterAmazerContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Letter> Letters { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<Coupon> Coupons { get; set; }
        public DbSet<OrderItem> OrderItems { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<FulfillmentPartner> FulfillmentPartners { get; set; }
        public DbSet<OfficeProductDetail> OfficeProductDetails { get; set; }
        public DbSet<OfficeProduct> OfficeProducts { get; set; }
        public DbSet<Office> Offices { get; set; }
        public DbSet<ProductMatrix> ProductMatrices { get; set; }
        public DbSet<ProductMatrixLine> ProductMatrixLines { get; set; }
        public DbSet<Shop> Shops { get; set; }
    }
}
