//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetterAmazer.Business.Services.Data
{
    using System;
    
    public enum LetterStatus : int
    {
        Created = 0,
        Sending = 1,
        Sent = 2,
        Returned = 3,
        Cancelled = 4
    }
}
