//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetterAmazer.Business.Services.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Letter
    {
        public Letter()
        {
            this.LetterDetails = new HashSet<LetterDetail>();
            this.FromAddress = new AddressInfo();
            this.ToAddress = new AddressInfo();
            this.LetterContent = new LetterContent();
        }
    
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public LetterStatus LetterStatus { get; set; }
        public int OrderId { get; set; }
    
        public AddressInfo FromAddress { get; set; }
        public AddressInfo ToAddress { get; set; }
        public LetterContent LetterContent { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<LetterDetail> LetterDetails { get; set; }
        public virtual Order Order { get; set; }
    }
}
