//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetterAmazer.Business.Services.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LetterDetail
    {
        public int Id { get; set; }
        public Color Color { get; set; }
        public LetterStatus LetterStatus { get; set; }
        public PaperQuality PaperQuality { get; set; }
        public PrintSize Size { get; set; }
        public PrintQuality PrintQuality { get; set; }
        public int LetterId { get; set; }
        public LetterQuatity LetterQuality { get; set; }
    
        public virtual Letter Letter { get; set; }
    }
}
