//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetterAmazer.Business.Services.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Office
    {
        public Office()
        {
            this.OfficeProducts = new HashSet<OfficeProduct>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CountryId { get; set; }
        public int PartnerId { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual FulfillmentPartner FulfillmentPartner { get; set; }
        public virtual ICollection<OfficeProduct> OfficeProducts { get; set; }
    }
}
