//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetterAmazer.Business.Services.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficeProduct
    {
        public int Id { get; set; }
        public int OfficeId { get; set; }
        public int ScopeType { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> ContinentId { get; set; }
        public Nullable<int> ZipId { get; set; }
        public int ProductDetailsId { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual OfficeProductDetail OfficeProductDetail { get; set; }
        public virtual Office Office { get; set; }
    }
}
