//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetterAmazer.Business.Services.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficeProductDetail
    {
        public OfficeProductDetail()
        {
            this.OfficeProducts = new HashSet<OfficeProduct>();
            this.ProductMatrices = new HashSet<ProductMatrix>();
        }
    
        public int Id { get; set; }
        public int DocumentType { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<int> Quality { get; set; }
        public Nullable<int> LetterType { get; set; }
    
        public virtual ICollection<OfficeProduct> OfficeProducts { get; set; }
        public virtual ICollection<ProductMatrix> ProductMatrices { get; set; }
    }
}
