//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetterAmazer.Business.Services.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int Id { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> LetterId { get; set; }
        public Nullable<int> OrderId { get; set; }
    
        public virtual Letter Letter { get; set; }
        public virtual Order Order { get; set; }
    }
}
