//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetterAmazer.Business.Services.Data
{
    using System;
    
    public enum OrderStatus : int
    {
        Created = 0,
        Paid = 1,
        InProgress = 2,
        Done = 3,
        Error = 4,
        Cancelled = 5
    }
}
