//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetterAmazer.Business.Services.Data
{
    using System;
    
    public enum PrintSize : int
    {
        A4 = 0,
        A3 = 1,
        A5 = 2,
        Letter = 3
    }
}
