//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetterAmazer.Business.Services.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMatrix
    {
        public ProductMatrix()
        {
            this.ProductMatrixLines = new HashSet<ProductMatrixLine>();
        }
    
        public int Id { get; set; }
        public int PriceType { get; set; }
        public int Span_lower { get; set; }
        public int Span_upper { get; set; }
        public int ProductDetailId { get; set; }
    
        public virtual OfficeProductDetail OfficeProductDetail { get; set; }
        public virtual ICollection<ProductMatrixLine> ProductMatrixLines { get; set; }
    }
}
