//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetterAmazer.Data.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbApiAccess
    {
        public int Id { get; set; }
        public int OrganisationId { get; set; }
        public string ApiKey { get; set; }
        public string ApiSecret { get; set; }

        public string Role { get; set; }
    
        public virtual DbOrganisation DbOrganisation { get; set; }
    }
}
