//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetterAmazer.Data.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbCountries
    {
        public DbCountries()
        {
            this.DbCustomers = new HashSet<DbCustomers>();
            this.DbLetters = new HashSet<DbLetters>();
            this.DbLetters1 = new HashSet<DbLetters>();
            this.DbOrganisationAddressList = new HashSet<DbOrganisationAddressList>();
        }
    
        public int Id { get; set; }
        public string CountryName { get; set; }
        public string CurrencyCode { get; set; }
        public string FipsCode { get; set; }
        public string CountryCode { get; set; }
        public string IsoNumeric { get; set; }
        public Nullable<double> North { get; set; }
        public string Capital { get; set; }
        public string ContinentName { get; set; }
        public string AreaInSqKm { get; set; }
        public string Languages { get; set; }
        public string IsoAlpha3 { get; set; }
        public string Continent { get; set; }
        public Nullable<double> South { get; set; }
        public Nullable<double> East { get; set; }
        public Nullable<int> GeonameId { get; set; }
        public Nullable<double> West { get; set; }
        public string Population { get; set; }
        public Nullable<bool> InsideEu { get; set; }
        public Nullable<int> ContinentId { get; set; }
    
        public virtual ICollection<DbCustomers> DbCustomers { get; set; }
        public virtual ICollection<DbLetters> DbLetters { get; set; }
        public virtual ICollection<DbLetters> DbLetters1 { get; set; }
        public virtual DbOffices DbOffices { get; set; }
        public virtual DbShops DbShops { get; set; }
        public virtual ICollection<DbOrganisationAddressList> DbOrganisationAddressList { get; set; }
    }
}
