//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetterAmazer.Data.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbEnvelopes
    {
        public DbEnvelopes()
        {
            this.DbEnvelopeWindows = new HashSet<DbEnvelopeWindows>();
        }
    
        public int Id { get; set; }
        public string Label { get; set; }
        public string ImagePath { get; set; }
        public Nullable<decimal> LengthInCm { get; set; }
        public Nullable<decimal> HeightInCm { get; set; }
        public Nullable<decimal> ThicknessInCm { get; set; }
        public Nullable<int> MaxPages { get; set; }
        public int EnvelopeType { get; set; }
        public Nullable<decimal> EnvelopeWeightInGm { get; set; }
    
        public virtual ICollection<DbEnvelopeWindows> DbEnvelopeWindows { get; set; }
    }
}
