//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetterAmazer.Data.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbEnvelopeWindows
    {
        public int Id { get; set; }
        public int EnvelopeId { get; set; }
        public int LetterSize { get; set; }
        public int WindowXOffset { get; set; }
        public int WindowYOffset { get; set; }
        public int WindowLength { get; set; }
        public int WindowHeight { get; set; }
    
        public virtual DbEnvelopes DbEnvelopes { get; set; }
    }
}
