//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetterAmazer.Data.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbExchangeRates
    {
        public int Id { get; set; }
        public System.DateTime DateFetched { get; set; }
        public int CurrencyId { get; set; }
        public decimal ExchangeRate { get; set; }
    }
}
