//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetterAmazer.Data.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbFulfillmentPartners
    {
        public DbFulfillmentPartners()
        {
            this.DbOffices = new HashSet<DbOffices>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int ShopId { get; set; }
    
        public virtual DbShops DbShops { get; set; }
        public virtual ICollection<DbOffices> DbOffices { get; set; }
    }
}
