//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetterAmazer.Data.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbInvoices
    {
        public DbInvoices()
        {
            this.DbInvoiceLines = new HashSet<DbInvoiceLines>();
        }
    
        public int Id { get; set; }
        public System.Guid Guid { get; set; }
        public int OrderId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateDue { get; set; }
        public int InvoiceStatus { get; set; }
        public string InvoiceNumber { get; set; }
        public int OrganisationId { get; set; }
        public decimal PriceExVat { get; set; }
        public decimal PriceVatPercentage { get; set; }
        public decimal PriceTotal { get; set; }
        public string Receiver_Organisation { get; set; }
        public string Receiver_AttPerson { get; set; }
        public string Receiver_Address1 { get; set; }
        public string Receiver_Address2 { get; set; }
        public string Receiver_City { get; set; }
        public string Receiver_Zipcode { get; set; }
        public string Receiver_State { get; set; }
        public int Receiver_CountryId { get; set; }
        public string Invoice_Organisation { get; set; }
        public string Invoice_AttPerson { get; set; }
        public string Invoice_Address1 { get; set; }
        public string Invoice_Address2 { get; set; }
        public string Invoice_City { get; set; }
        public string Invoice_Zipcode { get; set; }
        public string Invoice_State { get; set; }
        public int Invoice_CountryId { get; set; }
        public string Invoice_Vatnumber { get; set; }
        public string Receiver_Vatnumber { get; set; }
        public decimal PriceVat { get; set; }
        public decimal PriceVat1 { get; set; }
    
        public virtual ICollection<DbInvoiceLines> DbInvoiceLines { get; set; }
        public virtual DbOrders DbOrders { get; set; }
    }
}
