//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetterAmazer.Data.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbLeads
    {
        public int Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public int LeadStatus { get; set; }
        public string OrganisatioName { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string LettersPrWeek { get; set; }
        public string PhoneNumber { get; set; }
        public string CountryName { get; set; }
    }
}
