//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetterAmazer.Data.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbOfficeProductDetails
    {
        public DbOfficeProductDetails()
        {
            this.DbOfficeProducts = new HashSet<DbOfficeProducts>();
        }
    
        public int Id { get; set; }
        public int LetterColor { get; set; }
        public int LetterPaperWeight { get; set; }
        public int LetterProcessing { get; set; }
        public int LetterSize { get; set; }
        public int LetterType { get; set; }
    
        public virtual ICollection<DbOfficeProducts> DbOfficeProducts { get; set; }
    }
}
