//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetterAmazer.Data.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbOffices
    {
        public DbOffices()
        {
            this.DbOfficeProducts = new HashSet<DbOfficeProducts>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CountryId { get; set; }
        public int PartnerId { get; set; }
    
        public virtual DbCountries DbCountries { get; set; }
        public virtual DbFulfillmentPartners DbFulfillmentPartners { get; set; }
        public virtual ICollection<DbOfficeProducts> DbOfficeProducts { get; set; }
    }
}
