//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetterAmazer.Data.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbOfficeProducts
    {
        public DbOfficeProducts()
        {
            this.DbLetters = new HashSet<DbLetters>();
        }
    
        public int Id { get; set; }
        public int OfficeId { get; set; }
        public int ScopeType { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> ContinentId { get; set; }
        public Nullable<int> ZipId { get; set; }
        public int ProductDetailsId { get; set; }
        public int ReferenceType { get; set; }
        public int LetterColor { get; set; }
        public int LetterPaperWeight { get; set; }
        public int LetterProcessing { get; set; }
        public int LetterSize { get; set; }
        public int LetterType { get; set; }
    
        public virtual ICollection<DbLetters> DbLetters { get; set; }
        public virtual DbOffices DbOffices { get; set; }
    }
}
