//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetterAmazer.Data.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbOfficeProductDetails
    {
        public DbOfficeProductDetails()
        {
            this.DbOfficeProducts = new HashSet<DbOfficeProducts>();
            this.DbProductMatrix = new HashSet<DbProductMatrix>();
        }
    
        public int Id { get; set; }
        public int DocumentType { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<int> Quality { get; set; }
        public Nullable<int> LetterType { get; set; }
    
        public virtual ICollection<DbOfficeProducts> DbOfficeProducts { get; set; }
        public virtual ICollection<DbProductMatrix> DbProductMatrix { get; set; }
    }
}
