//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetterAmazer.Data.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbOrganisationProfileSettings
    {
        public int Id { get; set; }
        public int OrganisationId { get; set; }
        public Nullable<int> LetterColor { get; set; }
        public Nullable<int> LetterProcessing { get; set; }
        public Nullable<int> LetterPaperWeight { get; set; }
        public Nullable<int> LetterType { get; set; }
        public Nullable<int> LetterSize { get; set; }
        public Nullable<int> PreferedCountryId { get; set; }
    
        public virtual DbOrganisation DbOrganisation { get; set; }
    }
}
