//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetterAmazer.Data.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbOrders
    {
        public DbOrders()
        {
            this.DbInvoices = new HashSet<DbInvoices>();
            this.DbLetters = new HashSet<DbLetters>();
            this.DbOrderlines = new HashSet<DbOrderlines>();
        }
    
        public int Id { get; set; }
        public int OrderStatus { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public System.Guid Guid { get; set; }
        public string OrderCode { get; set; }
        public string TransactionCode { get; set; }
        public decimal PriceExVat { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<System.DateTime> DatePaid { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
        public decimal VatPercentage { get; set; }
        public decimal Total { get; set; }
    
        public virtual DbCustomers DbCustomers { get; set; }
        public virtual ICollection<DbInvoices> DbInvoices { get; set; }
        public virtual ICollection<DbLetters> DbLetters { get; set; }
        public virtual ICollection<DbOrderlines> DbOrderlines { get; set; }
    }
}
