//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetterAmazer.Data.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbPaymentMethods
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public int MinimumAmount { get; set; }
        public int MaximumAmount { get; set; }
        public decimal Price { get; set; }
        public int SortOrder { get; set; }
        public bool IsVisible { get; set; }
        public bool RequiresLogin { get; set; }
    }
}
