//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetterAmazer.Data.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbPartnerTransactions
    {
        public int Id { get; set; }
        public int PartnerId { get; set; }
        public int CustomerId { get; set; }
        public int ValueId { get; set; }
        public int OrderId { get; set; }
    
        public virtual DbCustomers DbCustomers { get; set; }
        public virtual DbPartners DbPartners { get; set; }
    }
}
