//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetterAmazer.Websites.Client.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LetterAmazer.Websites.Client.Resources.Views.Home.ViewRes", typeof(ViewRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;We decided to start LetterAmazer to make letters easy. Our overall vision is to be &lt;b&gt;friendly&lt;/b&gt;. When you use our service or call us, you should feel &lt;b&gt;welcome!&lt;/b&gt;&lt;/p&gt;
        ///
        ///            &lt;p&gt;We&apos;ve made it extremely simple to send a single letter, with no extra charges just because you don&apos;t want to register a new account. For businesses it is extremely simple to use, with many ways of integrating to our service.&lt;/p&gt;
        ///
        ///            &lt;p&gt;We are two guys from Denmark. Lars Holdgaard is the tech-wizard and wor [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutUsContent {
            get {
                return ResourceManager.GetString("AboutUsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add voucher.
        /// </summary>
        public static string AddVoucher {
            get {
                return ResourceManager.GetString("AddVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api.
        /// </summary>
        public static string Api {
            get {
                return ResourceManager.GetString("Api", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;We are currently developing an API, so our system can be integrated into any software application or website. That means if you need automated physical letters, we are there to provide it.&lt;/p&gt;
        ///
        ///            &lt;p&gt;We promise it will be an extremely simple REST API, and we expect it to be up in December 2013 or January 2014.&lt;/p&gt;
        ///
        ///            &lt;p&gt;Frankly, we hate FAQ&apos;s, where business owners invent their own questions and answer them by a sales speech. However, we will try to answer some of the obvious quest [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ApiContent {
            get {
                return ResourceManager.GetString("ApiContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API to send physical letters automatically.
        /// </summary>
        public static string ApiHint {
            get {
                return ResourceManager.GetString("ApiHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business.
        /// </summary>
        public static string Business {
            get {
                return ResourceManager.GetString("Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;No employee loves the tiresome process of sending those physical letters. Let&apos;s make everyone&apos;s lives easier, and let us send them for you. Heck, it&apos;s probably even cheaper (and much cheaper if you count in the hourly wage).&lt;/p&gt;
        ///
        ///            &lt;p&gt;As a business, you can either use our easy &quot;send a letter&quot; form, and then pay every time you need send a letter, &lt;b&gt;or&lt;/b&gt; you can create an account. If you create an account, you can add credits, and then get a friendly e-mail when your credits are running out. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BusinessContent {
            get {
                return ResourceManager.GetString("BusinessContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send physical letters online for businesses.
        /// </summary>
        public static string BusinessHint {
            get {
                return ResourceManager.GetString("BusinessHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmPassword.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string Faq {
            get {
                return ResourceManager.GetString("Faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For business.
        /// </summary>
        public static string ForBusiness {
            get {
                return ResourceManager.GetString("ForBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Need to send a lot of letters? Need to integrate letters into an application? You&apos;ve arrived at the right place.&lt;/p&gt;
        ///            &lt;p&gt;We provide a backend to companies who need to send multiple letters, which you with ease can use in your business. And yes, we send world-wide.&lt;/p&gt;.
        /// </summary>
        public static string ForBusinessContent {
            get {
                return ResourceManager.GetString("ForBusinessContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get updates.
        /// </summary>
        public static string GetUpdates {
            get {
                return ResourceManager.GetString("GetUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;b style=&quot;font-size: 16px; font-weight: bold;&quot;&gt;We don&apos;t get it.&lt;/b&gt;&lt;/p&gt;
        ///            &lt;p&gt;15 Years ago we were blessed with the invention of e-mail, and communication has been extremely easy since. However, we all send physical letters from time to time. &lt;/p&gt;
        ///
        ///            &lt;p&gt;Sending physical letters is so tiresome. First you have to &lt;strong&gt;buy some windowed envelopes&lt;/strong&gt;. Then you have to &lt;strong&gt;manually adjust the document&lt;/strong&gt;, so the recipients address fit the window in the envelope. Then y [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HomepageContent {
            get {
                return ResourceManager.GetString("HomepageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super fast, and absolutely free to get going.
        /// </summary>
        public static string LoginHint {
            get {
                return ResourceManager.GetString("LoginHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;frontpageLead&quot;&gt;Fantastic!&lt;br/&gt;Please click on url in your email and start to recover password.&lt;/p&gt;.
        /// </summary>
        public static string PleaseCheckEmailAndStartToRecoverPassword {
            get {
                return ResourceManager.GetString("PleaseCheckEmailAndStartToRecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing.
        /// </summary>
        public static string Pricing {
            get {
                return ResourceManager.GetString("Pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;So, when we started LetterAmazer, we found out sending letters isn&apos;t free. But! We have done anything in our power to find the cheapest prices, so you can send letters world-wide cheaply.&lt;/p&gt;
        ///
        ///            &lt;p&gt;
        ///                Our price structure is really simple:&lt;br /&gt;
        ///                &lt;b&gt;1.75 USD pr. letter (world wide)&lt;/b&gt;
        ///            &lt;/p&gt;
        ///
        ///            &lt;p&gt;
        ///                If you need to send additional pages:&lt;br /&gt;
        ///                1 page: 1.75 USD&lt;br /&gt;
        ///                2 pages: 1.95 USD&lt;br /&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PricingContent {
            get {
                return ResourceManager.GetString("PricingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prices to send physical letters around the globe.
        /// </summary>
        public static string PricingHint {
            get {
                return ResourceManager.GetString("PricingHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;We have providers in all regions of the world, which means we get the cheapest prices.&lt;/p&gt;
        ///            &lt;p&gt;We constantly try to push the prices down, so we have the most competitive prices on the market.&lt;/p&gt;.
        /// </summary>
        public static string PricingHomepageContent {
            get {
                return ResourceManager.GetString("PricingHomepageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;frontpageLead&quot;&gt;Fantastic!&lt;br/&gt;Your account is registered.&lt;/p&gt;           .
        /// </summary>
        public static string RegisterSuccessContent {
            get {
                return ResourceManager.GetString("RegisterSuccessContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send letters world-wide, automatically.
        /// </summary>
        public static string SendLettersWorldWideAutomatically {
            get {
                return ResourceManager.GetString("SendLettersWorldWideAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a single letter.
        /// </summary>
        public static string SendSingleALetter {
            get {
                return ResourceManager.GetString("SendSingleALetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Want to send a letter to someone? It is very easy, and your letter should be on its way within 5 minutes.&lt;/p&gt;
        ///            &lt;p&gt;You can either use our online text-formatter, or simply upload a PDF file. Then we will take care of your letter, and make sure it arrives as soon as possible.&lt;/p&gt;.
        /// </summary>
        public static string SendSingleALetterContent {
            get {
                return ResourceManager.GetString("SendSingleALetterContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View details.
        /// </summary>
        public static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
    }
}
